search_space:
  batch_size: 
    _type: choice
    _value: [ 256, 512 ]
  epochs: 
    _type: choice
    _value: [ 1,  2 ]
  seq: 
    _type: choice
    _value: [ 15 ]
    # lr: 
    #   _type: choice,
    #   _value: [0.01, 0.001, 0.0001],
    # hidden_units:   
    #   _type: choice,
    #   _value: [32, 64, 128, 256],
    # dropout_rate: 
    #   _type: uniform,
    #   _value: [0.5, 0.7],
  path: 
    _type: choice
    _value: [ "./data/kdd17/ourpped/" ]
    # seq: 
    #   _type: uniform,
    #   _value: [5, 10],